version: "3.4"
services:
  prisma:
    image: prismagraphql/prisma:1.17
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
            database: testic
  postgres:
    image: postgres:10.5
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: testic
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"

volumes:
  dbdata:
    name: prismaTestDB
